### ISSUE TITLE
GHE support

### ISSUE THREAD

**Issue by anton-rudeshko** [octokit/app.js#13]
Hi there!

Thanks for the awesome library here.

Currently I'm struggling with using it as a base for our Node.JS internal GHE Apps. Got an error `Integration must generate a public key`. I found a relevant https://github.com/octokit/octokit.rb/issues/1080.

But for now base url seems hardcoded to `https://api.github.com` through `@octokit/request` and I can't see a way it can be overwritten from app.js instance.

Am I missing something?

Do you have any plans to support GHE endpoints?

Or would you accept a PR for this behaviour?

Thanks!

**Comment by gr2m** [comment]
> But for now base url seems hardcoded to `https://api.github.com` through `@octokit/request` and I can't see a way it can be overwritten from app.js instance.

Oh my, that was a total oversight, thank you for opening the issue! 

Do you think you could send a PR for it? The [`@octokit/request`](https://github.com/octokit/request.js) library that is used to send requests to GitHub supports a [`.default()`](https://github.com/octokit/request.js#octokitrequestdefaults) method that can be used to set the baseUrl to an GitHub Enterprise instance based on options passed to the constructor

**Comment by anton-rudeshko** [comment]
@gr2m please see #14.
