### ISSUE TITLE
Migration guide to v10?

### ISSUE THREAD

**Issue by wereHamster** [octokit/app.js#150]
I have an app which uses `getInstallationAccessToken()`, and that function is not available anymore in the new version v10. I would appreciate a migration guide which explains how to migrate my code.

**Comment by gr2m** [comment]
you can find the migration guide in the README of the previous version:
https://github.com/octokit/app.js/tree/v4.3.0#%EF%B8%8F-deprecated

You want to migrate to `@octokit/auth-app`, not v10 of `@octokit/app`. Before v10, `@octokit/app` was just a means of receiving authentication tokens. It now is a fully fledged API to send requests, iterate through all installations/repositories, handle webhook requests and oauth flows.
