### ISSUE TITLE
Error when compiling 2.2.1 with typescript 2.8.3 

### ISSUE THREAD

**Issue by nbransby** [octokit/app.js#18]
node_modules/@octokit/app/index.d.ts(1,22): error TS7016: Could not find a declaration file for module 'lru-cache'. 'C:/code/functions/node_modules/lru-cache/index.js' implicitly has an 'any' type.
  Try `npm install @types/lru-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'lru-cache';`

**Comment by wolfy1339** [comment]
Thanks for reporting this. Have you tried installing the package as the error message suggests

**Comment by nbransby** [comment]
Yes that fixes it - guess you need to add it as a dependency your end

**Comment by wolfy1339** [comment]
Hey @gr2m, can you add this to the dependencies?

**Comment by gr2m** [comment]
This would be a dev dependency, right? I’m still out on vacation until Thursday, if someone could start a pull request it would speed things up, I’m mostly checking notifications on my phone right now

**Comment by wolfy1339** [comment]
I think so
________________________________

**Comment by gr2m** [comment]
So I'm not sure what the right thing to do is here. If I add it as a dev dependency that people using the library would not get it. So I guess I add it as a production dependency, as `lru-cache` is one, too?

**Comment by wolfy1339** [comment]
Closed by #22

**Comment by gr2m** [comment]
roger roger
