### ISSUE TITLE
is-plain-object' do not define a valid '.' target

### ISSUE THREAD

**Issue by thellimist** [octokit/app.js#187]
`Error: Package exports for '/app/node_modules/@octokit/endpoint/node_modules/is-plain-object' do not define a valid '.' target`

After updating from library version v4.1.0 to v10+ I'm getting this issue. I have added https://github.com/octokit/auth-app.js as well for legacy code, but the error remains when trying to compile (using Typescript).

**Comment by gr2m** [comment]
beware that v10 has nothing todo with v4, it's an entirely different library now. I'd replace `@octokit/app` with `@octokit/auth-app` altogether.

I've seen this error occur in the past if there were different versions of `is-plain-object` in your dependency tree. I think the last time I've seen it the people were using `pkg` to package up an app for lambda

**Comment by thellimist** [comment]
> I'd replace @octokit/app with @octokit/auth-app altogether.

The error was AFTER doing the migration


>I've seen this error occur in the past if there were different versions of is-plain-object in your dependency tree. I think the last time I've seen it the people were using pkg to package up an app for lambda

I'm not using `pkg` or lambda. It's straight forward nodejs app. I have moved forward by implementing the OAuth functionality myself.

**Comment by gr2m** [comment]
the new `@octokit/app` implements OAuth APIs. If you only need the OAuth APIs, you might like https://github.com/octokit/oauth-app.js
