### ISSUE TITLE
app.eachRepository does not support installation ID argument

### ISSUE THREAD

**Issue by tmadeira** [octokit/app.js#188]
According to README, users can _optionally pass installation ID to iterate through all repositories in one installation_ to `app.eachRepository`:

```js
for await (const { octokit, repository } of app.eachRepository.iterator({ installationId })) { /* ... */ }
await app.eachRepository({ installationId }, ({ octokit, repository }) => /* ... */)
```

That seems to be important -- to avoid fetching all repositories of all installations when you only want to iterate through repositories of a specific installation --, but it does not seem to be implemented (https://github.com/octokit/app.js/blob/master/src/each-repository.ts).

**Comment by gr2m** [comment]
Indeed, sorry for that! 

I can look into it myself in a week. If you'd like to send a pull request, I'd be happy to review it beforehand. You can start with just a failing test, and we take it from there?

**Comment by tmadeira** [comment]
Hi @gr2m, thank you for the quick response. I sent a PR (#189) with the regression test and an implementation. Struggled a little bit with method overloading, but hope it's ok.
