### ISSUE TITLE
TypeScript build error: Return type of exported function has or is using name 'BaseWebhookEvent' from external module "/Users/gregor/Projects/octokit/app.js/node_modules/@octokit/webhooks/dist-types/types" but cannot be named.

### ISSUE THREAD

**Issue by gr2m** [octokit/app.js#200]
Occurred here after upgrading to `@octokit/webhooks` v8:
https://github.com/octokit/app.js/runs/1858152718?check_suite_focus=true#step:5:14

```
node_modules/typescript/bin/tsc --outDir pkg/dist-src/ -d --declarationDir pkg/dist-types/ --project tsconfig.json --target es2020 --module esnext --noEmit false --sourceMap false
src/webhooks.ts:8:17 - error TS4058: Return type of exported function has or is using name 'BaseWebhookEvent' from external module "node_modules/@octokit/webhooks/dist-types/types" but cannot be named.

8 export function webhooks(
                  ~~~~~~~~
```

@G-Rath @wolfy1339 @oscard0m does that error ring a bell?

**Comment by G-Rath** [comment]
Yeah that's the error we got "that one time" - but our build is succeeding 🤔 

I can't look into this right this minute because of work, but will when I have a chance :)

**Comment by G-Rath** [comment]
btw you should be able to fix this by explicitly typing the return of the function - what's weird is that at a quick glance that function looks like its return type should be `Webhooks` 🤔 

At a guess, I'd say it's trying to generate a type for that, but by resolving all type aliases when it should be using `Webhooks` directly...

**Comment by oscard0m** [comment]
This is the related issue I found @G-Rath https://github.com/octokit/webhooks.js/pull/422

**Comment by oscard0m** [comment]
> btw you should be able to fix this by explicitly typing the return of the function - what's weird is that at a quick glance that function looks like its return type should be `Webhooks` 🤔
> 
> At a guess, I'd say it's trying to generate a type for that, but by resolving all type aliases when it should be using `Webhooks` directly...

This is how it looks hovering in CodeSpaces: 
![Uploading image.png…]()

**Comment by G-Rath** [comment]
Interesting, but tbh not surprising - it's the same thing as what was happening when we had this issue over at `@octokit/webhooks`: it's resolving it to a union of all 200 possible values you can pass to `BaseWebhookEvent`.

To change that you need to put an explicit return type on the function + implement the generic (so just copy the generic + constructor signatures from the `Webhook` class)
