### ISSUE TITLE
broken node 10/12 compatibility

### ISSUE THREAD

**Issue by raptordzuricsko** [octokit/app.js#296]
heya, we are using octokit for our cicd. It relies on an older version of node and upgrading node would require us to fork upstream projects. 

It looks like between 12.0.5 and 12.0.6 in these commits https://github.com/octokit/webhooks.js/pull/555/files and https://github.com/octokit/webhooks.js/commit/e887f0588a5ade28e21f75b34fcc60effd2f5ec4 , node support was removed for 10/12 in the webhooks library. This is cool and exciting! It also has taken down our CI platform's ability to run CI builds at all by breaking the upstream proj's use of octokit. Our CI platform shells out to `yarn add` to grab dependencies for CI glue code.

Would it be possible to push a patch version that is compatible with node 10/12? Then make a major release that discontinues support for node 10/12?

We tried to do some npm/yarn resolutions stuff https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/ but are stuck on an old yarn version too. We are definitely doing our best to prioritize this stuff but it is an old wide reaching CI system(we're actively migrating projects to a new CI system but have some ways to go).

thank you! let me know if you need any more information

**Comment by wolfy1339** [comment]
Thanks for bringing this up!

We can definitely remedy the situation by reverting the change and publish a new major version.

We are currently in the process of dropping support for Node v10 and v12 across all Octokit packages, so things can be missed
