### ISSUE TITLE
[FEAT]: Docs? 

### ISSUE THREAD

**Issue by alexyoung23j** [octokit/app.js#363]
### Describe the need

Are there any docs for this library? Having trouble locating them, I see a bunch of octokit stuff but not for this app package. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The documentation for this package is located in the README.md file.

You can also find some documentation for it in the [`octokit` package's README](https://github.com/octokit/octokit.js/#app-client).

All this package does is provide the way to authenticate to the GitHub API as an app.
