### ISSUE TITLE
Please document: is default cache global or specific to instantiation?

### ISSUE THREAD

**Issue by chrishiestand** [octokit/app.js#37]
From the code it looks like the cache is specific to the instantiation of `new App()`. Could you confirm? Thanks.

**Comment by gr2m** [comment]
Yes, they are per instance

https://github.com/octokit/app.js/blob/9a8c2f2d366f381a1e314eb05fe6fed344db492e/src/index.ts#L15

If you want to a global cache you can pass in your own cache API as documented. I’ll start a PR to qualify

**Comment by wolfy1339** [comment]
Fixed by #39
