### ISSUE TITLE
[DOCS]: How to `@octokit/graphql`?

### ISSUE THREAD

**Issue by axecopfire** [octokit/app.js#379]
### Describe the need

How can I get this to work with `@octokit/graphql`

https://www.npmjs.com/package/@octokit/graphql#authentication

```typescript
import { Octokit } from "@octokit/rest";
import { graphql } from "@octokit/graphql";
import { App } from "@octokit/app";

const octokit = async () => {
  const app = new App({
    appId: process.env.GITHUB_APP_ID ?? "",
    privateKey: process.env.GITHUB_PRIVATE_KEY ?? "",
    oauth: {
      clientId: process.env.GITHUB_CLIENT_ID ?? "",
      clientSecret: process.env.GITHUB_CLIENT_SECRET ?? "",
    },
    Octokit,
  });
  let installationId = 123;

  for await (const { installation } of app.eachInstallation.iterator()) {
    installationId = installation.id;
  }

  const octokit = await app.getInstallationOctokit(installationId);

  const graphqlWithAuth = graphql.defaults({
    request: {
      hook: octokit.hook,
    },
  });

  return {
    ...octokit,
    graphql: graphqlWithAuth,
  };
};

```

Error I'm receiving: `error - Error: method for before hook must be a function`

Which I believe is coming from this [webhook line](https://github.com/octokit/app.js/blob/3e44c5d6ee9e3bd346afc01979953ca7848625b2/src/webhooks.ts#L58)

The reason I'm looking for `octokit.hook` is because the `@octokit/graphql` docs show a `hook` as the way to auth.

```typescript
const { createAppAuth } = require("@octokit/auth-app");
const auth = createAppAuth({
  appId: process.env.APP_ID,
  privateKey: process.env.PRIVATE_KEY,
  installationId: 123,
});
const graphqlWithAuth = graphql.defaults({
  request: {
    hook: auth.hook,
  },
});

```

I believe that I'm going to need to load in `@octokit/auth-app` as well to be able to `graphql` auth. I just want to make sure that's what is expected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by axecopfire** [comment]
How I got this to work was by doing a second auth for Graphql and attached the authed Graphql instance as a property to the app.

```typescript
import { Octokit } from "@octokit/rest";
import { graphql } from "@octokit/graphql";
import { App } from "@octokit/app";
import { createAppAuth } from "@octokit/auth-app";

const octokit = async () => {
  const app = new App({
    appId: `<VARIABLE>`,
    privateKey: `<VARIABLE>`,
    oauth: {
      clientId: `<VARIABLE>`,
      clientSecret: `<VARIABLE>`,
    },
    Octokit,
  });
  let installationId = 123;

  for await (const { installation } of app.eachInstallation.iterator()) {
    installationId = installation.id;
  }

  const octokit = await app.getInstallationOctokit(installationId);

  // Graphql auth
  const oauth = createAppAuth({
    appId: `<VARIABLE>`,
    privateKey: `<VARIABLE>`,
    installationId,
  });

  const graphqlWithAuth = graphql.defaults({
    request: {
      hook: oauth.hook,
    },
  });

  return {
    ...octokit,
    graphql: graphqlWithAuth,
  };
};

export default octokit;
```

**Comment by gr2m** [comment]
```js
import { App } from "octokit";

run()

async function run () {
  const app = new App({
    appId: process.env.GITHUB_APP_ID,
    privateKey: process.env.GITHUB_PRIVATE_KEY,
  });

  const octokit = await app.getInstallationOctokit(process.env.GITHUB_INSTALLATION_ID);
  await octokit.graphql( /* ... */ )  
};
```

If you don't know the installation ID, you can retrieve for the [user](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-a-user-installation-for-the-authenticated-app), [organization](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-organization-installation-for-the-authenticated-app), or [repository](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-a-repository-installation-for-the-authenticated-app). For example:

```js
const { data: installation } = await app.octokit.request('GET /repos/{owner}/{repo}/installation', {
  owner: 'OWNER',
  repo: 'REPO'
})
// installation.id
```

**Comment by axecopfire** [comment]
I don't know what my `installationId` is in this example, agreed I could get that from env vars. However, in your example you are saying that `app.getInstallationOctokit` returns a `graphql` method, which is something I didn't experience. Maybe I was doing something wrong, I can go check.

**Comment by gr2m** [comment]
`app.getInstallationOctokit()` returns an `Octokit` instance, which always includes the `.graphql()` method?

I'll close the issue as there is nothing actionable left to do, but feel free to continue to comment if you have follow up questions
