### ISSUE TITLE
Is there any retry functionality?

### ISSUE THREAD

**Issue by mattkime** [octokit/app.js#41]
I'm curious if there's any retry functionality available as there is for the rest.js API. Retry is necessary due to network instability with github.

**Comment by gr2m** [comment]
I’m afraid not at this point, but thank you for raising the question 👍 

I think the right approach would be to accept `request` as a constructor option so you can override the internally used `request()` method. That method could be `octokit.request` from `@octokit/rest` or we could even look into implementing a hook to make retries work with `@octokit/request` itself, as it now supports a `hook` option which should suffice for that, see https://github.com/octokit/request.js#request

![image](https://user-images.githubusercontent.com/39992/60126395-bf062f00-9742-11e9-8faa-cbd75dc91d09.png)

I’m currently working on https://github.com/octokit/auth-app.js as part of https://github.com/octokit/auth.js which will replace the current `@octokit/app`. I’ll make sure to consider your use case there.

If this is a blocking issue for you, I’d welcome a pull request adding a `request` constructor option to the current `@octokit/app`

**Comment by mattkime** [comment]
I used https://github.com/zeit/async-retry - https://github.com/elastic/github-checks-reporter/commit/6b990b515f0b22d7ff94674381922e41f6d548da

The code is a little messy but it gets the job done. I do like the idea of having a general purpose async retry but I find the syntax to be a little obtuse. But maybe thats just because I'm new to it. 

I don't necessarily think this needs to be solved in octokit/* but it might be sufficient to show how to use another package to do it.

**Comment by gr2m** [comment]
This library is going to be deprecated in favor of https://github.com/octokit/auth-app.js, which supports a `request` option for a custom request method.

You can do this

```js
import { Octokit } from '@octokit/core'
import { createAppAuth } from '@octokit/auth-app'
import { retry } from '@octokit/plugin-retry'

const MyAppOctokit = Octokit.plugin(retry).defaults({ authStrategy: createAppAuth })
const octokit = new MyAppOctokit({
  id: APP_ID,
  privateKey: PRIVATE_KEY,
  /* optional */
  installationId: INSTALLATION_ID
})
```

That will use `octokit.request` within the `createAppAuth` strategy, which will do the retry from the plugin.
