### ISSUE TITLE
[MAINT]: Bump OAuth to v6.1.0

### ISSUE THREAD

**Issue by raferdev** [octokit/app.js#502]
### Describe the need

Just bump OAuth to be able to access the new types from the [v6.1.0](https://github.com/octokit/oauth-app.js/releases/tag/v6.1.0) version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The version range in this repository should already allow any version from the same major version to be installed.
Updating your lock files, or doing a fresh reinstall of the deps should pull it in

**Comment by raferdev** [comment]
> The version range in this repository should already allow any version from the same major version to be installed. Updating your lock files, or doing a fresh reinstall of the deps should pull it in

I tried it, but don't update the version here. But it makes sense, I will try again.

**Comment by nickfloyd** [comment]
Hey @raferdev did the fresh reinstall work for you?

**Comment by raferdev** [comment]
I tried now and see it was my fault for locking the package version. Thanks for sharing this knowledge; I didn't know it's possible to update the dependencies inside dependencies without bumping the parent version. :pray:
