### ISSUE TITLE
Customizable cache time for expiring tokens

### ISSUE THREAD

**Issue by rarkins** [octokit/app.js#52]
I noticed that the default LRU expiry is after 59 minutes. I'm sure there's plenty of apps who need a token with more than 1 minute validity, and a token expiring mid-way through an app's job is pretty confusing to debug, so it would be nice if the cache ttl could be configurable without needing to substitute an entirely new cache.

**Comment by gr2m** [comment]
You should request a new token with each request. What is your use case?

**Comment by rarkins** [comment]
Git cloning using the token. You can’t easily submit a new token for every single git operation. 

Also distributed systems with a central token dispatcher. Querying the (remote) dispatcher would increase work and latency substantially. 

I have several other reasons as well

**Comment by gr2m** [comment]
Okay, but the current expiry is 59 minutes as you write:
https://github.com/octokit/app.js/blob/99c02ba21a4ff19bf3e3fa03047492692b51b01b/src/get-cache.ts#L8-L9

GitHub expires them after 1h. There is no way to increase the expiration time I'm afraid. Or is there something else you want to do?

You can also pass in your own cache implementation

**Comment by gr2m** [comment]
This library is being deprecated in favor of https://github.com/octokit/auth-app.js/. It creates and renews the authentication token transparently
