### ISSUE TITLE
[FEAT]: method for generating installation url

### ISSUE THREAD

**Issue by rpmccarter** [octokit/app.js#541]
### Describe the need

We have multiple github apps - one for each environment of our service. We have an endpoint that simply returns the installation url for the github app. Right now, the endpoint looks something like this:

```ts
    const baseUrl = process.env.NODE_ENV === 'development'
      ? 'https://github.com/apps/mintlify-development/installations/new'
      : 'https://github.com/apps/mintlify/installations/new';

    const url = new URL(baseUrl);

    url.searchParams.append('state', stateString);

    return url.toString();
```

I wish we didn't have to hard-code the github app name or store it as an env var. I noticed that the `@octokit/oauth-app` package has a convenient method `app.getWebFlowAuthorizationUrl(options)` which generates the authorization URL. I looked for a similar function within the octokit app but wasn't able to find anything. Would be a neat little feature to have - happy to implement as well!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
what I usually do is to retrieve the app's HTML URL

```js
const { data: appInfo } = await app.octokit.request("GET /app")
const installUrl = `${appInfo.html_url}/installations/new`
```

Does that work for you?

**Comment by rpmccarter** [comment]
I could definitely use that instead, and the implementation of this method would probably look just like that, I just like the convenience of `app.getWebFlowAuthorizationUrl(options)` and wanted to check if it was something that could be added to the GitHub app - it's nice to be able to create the exact installation link without having to refer to the github api docs. If this is too trivial that's fine :)

**Comment by gr2m** [comment]
The OAuth URL method is coming from this package: https://github.com/octokit/oauth-methods.js. We don't have a counterpart with methods for apps, but worth thinking about.

I suggest we leave this issue open, maybe others can share their perspective and we can pick it up again in future

**Comment by rpmccarter** [comment]
Created PR #542 to address this, mostly for fun - let me know what you think!
