### ISSUE TITLE
Using self signed certificate with getInstallationAccessToken

### ISSUE THREAD

**Issue by b4nst** [octokit/app.js#57]
When using with GitHub Enterprise behind a self signed certificate, how can I pass a custom agent to `getInstallationAccessToken` as I  can do with `new Octokit({agent})` ?

**Comment by gr2m** [comment]
This should be possible with the new [@octokit/auth-app.js](https://github.com/octokit/auth-app.js/), I will deprecate this module soon in favor of `@octokit/auth-app.js`. 

`@octokit/auth-app.js` accepts a `request` option to which you can pass in the `octokit.request` method from your configured Octokit client: https://github.com/octokit/auth-app.js/#createappauthoptions

Does that work for you?

**Comment by b4nst** [comment]
Yep that should work for me, because in the meantime I used `octokit.request` (with a proper configured `https.Agent` and reforged the request found here :

https://github.com/octokit/app.js/blob/33b558da607298688d62448f3d3421dbc475fed8/src/get-installation-access-token.ts#L15-L26

and this worked. Thank you for pointing me the new module.
