### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by gr2m** [octokit/app.js#8]
`@octokit/app` could probably run in browsers, but the `jsonwebtoken` dependency increases the bundle size largely. There are alternative such as https://github.com/cisco/node-jose and https://github.com/square/js-jose which take advantage of the WebCrypto API. For Octokit, we only need  a slight subset of what these libraries provide, so it might be worth to build a custom package.

**Comment by wolfy1339** [comment]
With pika, this is no longer a problem. Though the bundle size is still a problem

**Comment by gr2m** [comment]
I think the bundle size is the only problem here, we can just leave it open. It would be a nice project to focus on the bundle and see how we can reduce its size.

**Comment by gr2m** [comment]
Fixed in `@octokit/auth-app`.

- old: https://bundlephobia.com/result?p=@octokit/app@4.1.1 (17.2kB)
- new: https://bundlephobia.com/result?p=@octokit/auth-app@2.4.2 (7.5kB)
